
const policyTxt = [
  {
    'title': 'Alcohol and Drugs Policy',
    'overview': 'Overview',
    'header': 'National Standing Policy adopted per NIC Policy 1/2020',
    'summary': 'By September 1, 2019, NIC member organizations will evaluate their documents to determine if they are consistent with the following guidelines. As autonomous and self-governing entities, member organizations have the latitude to codify these guidelines in a way that is consistent with their organization\'s nomenclature, operations, programming, etc. Member organizations are responsible for enforcing their own policies; the NIC does not play a role in policy enforcement.',
    'paragraphs': [
      'In any activity or event sponsored or endorsed by the chapter/organization, including those that occur on or off organizational/chapter premises:',
      '1. The chapter/organization, members and guests must comply with all federal, state, provincial and local laws. No person under the legal drinking age may possess, consume, provide or be provided alcoholic beverages.',
      '2. The chapter/organization, members and guests must follow the federal law regarding illegal drugs and controlled substances. No person may possess, use, provide, distribute, sell, and/or manufacture illegal drugs or other controlled substances while on chapter/organizational premises or at any activity or event sponsored or endorsed by the chapter/organization.',
      '3. Alcoholic beverages must either be:',
      '- Provided and sold on a per-drink basis by a licensed and insured third-party vendor (e.g., restaurant, bar, caterer, etc.); or',
      '- Brought by individual members and guests through a bring your own beverage (“BYOB”) system. The presence of alcohol products above 15% alcohol by volume (“ABV”) is prohibited on any chapter/organization premises or at any event, except when served by a licensed and insured third party vendor.',
      '4. Common sources of alcohol, including bulk quantities, which are not being served by a licensed and insured third party vendor, are prohibited (i.e., amounts of alcohol greater than what a reasonable person should consume over the duration of an event).',
      '5. Alcoholic beverages must not be purchased with chapter/organizational funds or funds pooled by members or guests (e.g., admission fees, cover fees, collecting funds through digital apps, etc.).',
      '6. A chapter/organization must not co-host or co-sponsor, or in any way participate in, an activity or event with another group or entity that purchases or provides alcohol.',
      '7. A chapter/organization must not co-host or co-sponsor an event with a bar, event promoter, or alcohol distributor; however, a chapter/organization may rent a bar, restaurant, or other licensed and insured third-party vendor to host a chapter/organization event.',
      '8. Attendance by non-members at any event where alcohol is present must be by invitation only, and the chapter/organization must utilize a guest list system. Attendance at events with alcohol is limited to a 3:1 maximum guest-to-member ratio, and must not exceed local fire or building code capacity of the chapter/organizational premises or host venue.',
      '9. Any event or activity related to the new member joining process (e.g., recruitment, intake, rush, etc.) must be substance free. No alcohol or drugs may be present if the event or activity is related to new member activities, meetings, or initiation into an organization, including but not limited to “bid night,” “big/little” events or activities, “family” events or activities, and any ritual or ceremony.',
      '10. The chapter/organization, members or guests must not permit, encourage, coerce, glorify or participate in any activities involving the rapid consumption of alcohol, such as drinking games.',
    ],
  },
  {
    'title': 'Anti-Hazing Policy',
    'overview': 'Overview',
    'header': 'National Standing Policy adopted by National Executive Board 5/2002 and amended 7/14/2010',
    'summary': 'Nu Alpha Kappa Fraternity, Inc. strictly adheres to any local, state, or federal jurisdictions that enforce anti-hazing laws.',
    'paragraphs': [
      'No chapter, brother, alumnus or affiliate shall conduct nor condone hazing activities. Hazing activities are constituted as, \“Any action taken or situation created, intentionally, whether on or off fraternity or university premises, to produce mental or physical discomfort, embarrassment, harassment, or ridicule. Such activities may include but are not limited to the following: use of alcohol; paddling in any form; creation of excessive fatigue; physical and psychological shocks; Non educational scavenger hunts, or any other such activities carried on outside or inside of the confines of the chapter; wearing of public apparel which is conspicuous and not normally in good taste; morally degrading or humiliating games and activities; and any other activities which are not consistent with academic achievement, fraternal law, or policy or the regulations and policies of the National Intake Process, or applicable state law.\“',
      'Hazing Defined',
      'Hazing is defined by the FIPG (Fraternal Information Programming Group) as:',
      'Any action taken or situation created, intentionally, whether on or off fraternity premises, to produce mental or physical discomfort, embarrassment, harassment, or ridicule. Such activities may include but are not limited to the following: use of alcohol; paddling in any form; creation of excessive fatigue; physical and psychological shocks; road trips or any other such activities carried on outside or inside of the confines of the chapter house; wearing of public apparel which is conspicuous and not normally in good taste; engaging in public stunts and buffoonery; morally degrading or humiliating games and activities; and any other activities which are not consistent with fraternal law, ritual or policy or the regulations and policies of the educational institution.',
      "Hazing refers to any activity expected of someone joining a group (or to maintain full status in a group) that humiliates, degrades or risks emotional and/or physical harm, regardless of the person's willingness to participate. In years past, hazing practices were typically considered harmless pranks or comical antics associated with young men in college fraternities.",
      'Today we know that hazing extends far beyond college fraternities and is experienced by boys/men and girls/women in school groups, university organizations, athletic teams, the military, and other social and professional organizations. Hazing is a complex social problem that is shaped by power dynamics operating in a group and/or organization and within a particular cultural context.',
      "Hazing activities are generally considered to be: physically abusive, hazardous, and/or sexually violating. The specific behaviors or activities within these categories vary widely among participants, groups and settings. While alcohol use is common in many types of hazing, other examples of typical hazing practices include: personal servitude; sleep deprivation and restrictions on personal hygiene; yelling, swearing and insulting new members/rookies; being forced to wear embarrassing or humiliating attire in public; consumption of vile substances or smearing of such on one's skin; brandings; physical beatings; binge drinking and drinking games; sexual simulation and sexual assault.",
      'Some common definitions and examples of hazing',
      'In the Alfred/NCAA survey of college athletes, hazing was defined as:',
      "Any activity expected of someone joining a group that humiliates, degrades, abuses or endangers, regardless of the person's willingness to participate. This does not include activities such as rookies carrying the balls, team parties with community games, or going out with your teammates, unless an atmosphere of humiliation, degradation, abuse or danger arises.",
      "Hazing is an activity that a high-status member orders other members to engage in or suggests that they engage in that in some way humbles a newcomer who lacks the power to resist, because he or she want to gain admission to a group. Hazing can be noncriminal, but it is nearly always against the rules of an institution, team, or Greek group. It can be criminal, which means that a state statute has been violated. This usually occurs when a pledging-related activity results in gross physical injury or death” (from Hank Nuwer's book Wrongs of Passage , 1999, p. xxv).",
      "If you have to ask if it's hazing, it is.",
      "If in doubt, call your advisor/coach/national office. If you won't pick up the phone, you have your answer. Don't B.S. yourself.",
      'If you haze, you have low self-esteem.',
      "If you allow hazing to occur, you are a 'hazing enabler.'",
      'Failure to stop hazing will result in death…”',
      'State Anti-Hazing Laws',
      'http://www.stophazing.org/policy/state-laws',
      'Violations of National Anti-Hazing Policy',
      'If the Intake Committee finds a chapter is in violation of the National Anti-Hazing Policy, that chapter would be suspended for one (1) academic year and would not be permitted to have an intake class for the next two academic years.',
      'Appeals:',
      'A. The chapter must submit a proposal to the National Intake Committee requesting permission to conduct an intake process after the two-year suspension is served.',
      "B. The National Intake committee will determine the status of the chapter's Intake (Pledge) class.",
      'Resources:',
      'HazingPrevention.org',
      'Hazing Prevention Presentation from AFA 20221 presented by Greek University',
      'Hazing Prevention Resources from Stop Hazing',
      'Love, Mom  & Dad: Turing tragedy into progress hosted by The Anti-Hazing Coalition',
    ],
  },
  {
    'title': 'Anti-Retaliation Policy',
    'overview': 'Overview',
    'header': 'Concerns involving an individual or chapter shall be reported to the National Executive Board via email (neb@nakinc.org) or through the NAK National Website – Incident Report',
    'summary': 'Nu Alpha Kappa Fraternity, Inc – a chapter and/or affiliated organization; prohibits retaliation against any individual – members and non-members – for reporting, inquiring, or cooperating with a report around a violation of the National Risk Management Policy.',
    'paragraphs': [
      'Retaliation is any action, statement, or behavior that is designed to punish an individual for filing a compliance report, cooperating with a compliance investigation, seeking guidance regarding a compliance concern, or to deter one from taking such action.',
    ],
  },
  {
    'title': 'Crisis Management Plan',
    'overview': 'Overview',
    'header': 'Procedures to be followed by the Chapter President in the event of an emergency or tragedy.',
    'summary': 'There are several recommended steps to follow in the event of an incident or tragedy, with some additional steps to follow in the event of a death of one of our brothers or prospective members or guests at a chapter sponsored event.r',
    'paragraphs': [
      '1.  WHO IS IN CHARGE DURING AN EMERGENCY?',
      'Be certain that each brother in your chapter knows that the chapter president, shall serve as the primary point of contact of every incident or emergency situation involving serious injury or death.  In the absence of the chapter president, the next ranking officer of the Chapter Executive Board, shall serve as a point of contact. Each chapter, should have this procedure written within their Chapter By-Laws and reviewed annually. At the beginning of each new leadership transition, this procedure shall include making arrangements with how to best contact the National President and chapter advisor(s).',
      '2.   EMERGENCY PHONE CALLS TO MAKE AND NUMBERS.',
      'You need to make several phone calls immediately',
      '1st: Call the appropriate local emergency number for an ambulance or police for assistance. If the emergency situation is a fire immediately call the fire department.',
      '2nd: Call National Executive Board (National President - president@nakinc.org) within 24 hours of incident.',
      '3rd: Call your Chapter Advisor and/or Greek Advisor within 24 hours of incident.',
      'This person will discuss the situation with you and in all serious cases will be at the location or chapter meeting place in a matter of minutes.  Always call, day or night, if you are in doubt as to whether a situation is serious or not.',
      '4th: Dependent on the nature of the incident, the National Executive Board shall contact our liability carrier to report the incident.',
      '3.  INFORMING MEMBERS, MAKING PUBLIC STATEMENTS.',
      'Assemble all active members in a group either in person or via video conference. Depending on the situation, brothers should be called to meet at a designated location.  It is important that all brothers remain calm during the crisis. Explain to them that there is an incident or emergency situation.  Ask them to cooperate in halting phone calls until the situation is under control. Do not discuss the situation until you have notified a National Executive Board member and/or your chapter advisor(s). Instruct your members to make no statements or post anything about or in regards to the incident on any social media platforms or discuss this matter with anyone without approval of the National Executive Board. The chapter president, will make any appropriate statements to the media after the situation is under control and shall have a discussion of the content of the statement with school and National Executive Board.  Make sure, however, that everyone knows what your statements will be.',
      '4.  WHEN A MEMBER IS INJURED, BECOMES SERIOUSLY ILL, OR DIES.',
      "Do not notify parents.  In the event of a serious accident or illness, the medical personnel will notify parents and advise them of the student's physical condition.  In the event of a death, the appropriate campus or National Executive Board official (National President) should notify parents.",
      "If the situation is a death outside the campus community (out of town), do not announce it until the National Executive Board or chapter advisor(s) has been notified or has arrived to help.  Be very careful about this information.  If the member was living with other members, do not move any of the individual's personal possessions. You should call the family to offer sympathy on behalf of the chapter. Ask what their wishes are in regard to the possessions of the member. You may offer to pack them in boxes, but chances are the parents will prefer to do this themselves.  Before they arrive, be sure that all borrowed items are returned to the member's room, and if possible, lock it.  When the parents do arrive, you may want to have empty boxes available and offer help.  This is an emotional trauma for parents so they may not want to be with any of their child's friends.",
      'It is, of course, proper to send sympathy cards and notes, flowers, etc.  If a funeral is not too distant, it would mean a great deal to parents for some of the members to attend.',
      '5.  IF A MEMBER ATTEMPTS SUICIDE.',
      'In the case of a suicide attempt, with or without serious injury, do not assemble your members or call parents. Please contact campus or local mental health support hotlines for additional assistance. Links to national support groups and other resources can be found under the Resources tab on the NAK National website.',
      '6.  OTHER POSSIBLE TRAGEDIES OR CRISIS. ',
      "Death of a Member of the Brother's Immediate Family - The chapter's reaction will likely be influenced by how the member himself reacts.  Flowers and a delegation to the funeral are certainly appropriate. The member will be shaken for some time following his loss.  The chapter must remain sensitive to this and assist in any way possible.",
      'A member is arrested - As much as possible, the active chapter should stand clear of any involvement.  In the case of the arresting crime was committed at a chapter sponsored event, steps 1-4 should be followed. Only the Chapter President should make comments to the public or media after adequate consultation with the National Executive Board, or chapter advisor.  In no case should chapter funds be used as bail money.',
      'All of this, no doubt, seems grim and harsh.  Everyone hopes that no Chapter President will ever have to use these procedures.  But sadly, that hope is not realistic.  Tragedies do occur. Usually, they are unpredictable.  You can ease the situation for all by being prepared to follow these procedures.',
    ],
  },
  {
    'title': 'Ethical Values Principles',
    'overview': 'Overview',
    'header': 'We, the members of Nu Alpha Kappa Fraternity, Inc., share a commitment to adhere to these principles of ethical values as partners to our campus community, supporters, and stakeholders in furtherance of our Mission Statement. ',
    'summary': '',
    'paragraphs': [
      'Integrity: We will conduct ourselves with integrity in our dealings with and on behalf of the organization.',
      'Accountability: We will be accountable as individuals and as members of our community and organization, in compliance with applicable laws, policies and directives set by local, state, federal, campus and national standards.',
      'Respect: We will respect the rights and dignity of others.',
    ],
  },
  {
    'title': 'Good Samaritan Policy',
    'overview': 'Overview',
    'header': 'The health and safety of our members and guests is of primary concern for Nu Alpha Kappa Fraternity, Inc.',
    'summary': 'Any time a member or guest is injured or displays signs of physical distress, our members have a duty to “do what ought to be done” by intervening to seek appropriate professional assistance for the person(s) in distress. Thus, Nu Alpha Kappa Fraternity, Inc. encourages its members to act as Good Samaritans.',
    'paragraphs': [
      'Calls 911 or seeks on-site assistance if such assistance is readily available.',
      'Stays with the person in distress until that party has been physically taken into the care of emergency service professionals (police, fire, ambulance, medical).',
      'Reports any incident involving the fraternity, a member or guest of a member to a National Executive Board Office (neb@nakinc.org) or via the NAK National Website – Incident Report.',
      'APPLYING THE GOOD SAMARITAN POLICY IF A RISK MANAGEMENT POLICY VIOLATION HAS OCCURRED:',
      'If the injury or distress occurred as a result of a violation(s) of Nu Alpha Kappa Fraternity National Risk Management Policy, which may include hazing, intoxication, and/or dangerous behaviors, an exercise of the Good Samaritan policy will be considered as extenuating circumstances.',
      'INVESTIGATION BY THE NATIONAL HEADQUARTERS AFTER AN EXERCISE OF THE GOOD SAMARITAN POLICY HAS BEEN REPORTED:',
      'The member(s) and/or chapter will cooperate with the Fraternity to determine whether a violation of the Nu Alpha Kappa Fraternity National Risk Management Policy occurred.',
      'If the chapter followed the Good Samaritan Policy , that may be used to appropriately adjust the educational sanctions imposed upon the chapter or member(s).',
      'THE GOOD SAMARITAN POLICY IS NOT INVOKED IF ANY OF THE FOLLOWING OCCUR:',
      'Members wait until the police or other authorities arrive before seeking appropriate emergency assistance.',
      'If the emergency personnel are summoned by the police.',
      'The incident is reported to Nu Alpha Kappa Fraternity, Inc. National Headquarters by someone other than the chapter or individual member(s) seeking to utilize the Good Samaritan Policy.',
    ],
  },
  {
    'title': 'Risk Management Education',
    'overview': 'Overview',
    'header': 'Education Program Overview',
    'summary': "It is strongly recommended by the North American Interfraternity Conference and Holmes Murphy & Associates to have an ongoing educational program. A year-round agenda should feature topics in risk management that address and explain current issues faced by the university's students. Topics should be reviewed on an annual basis to keep your chapter programming up to date as issues change. Upon completion of each educational program, a report should be submitted to the National Executive Board to verify completion. If programs are not completed by the National Executive Board's deadlines (prior to start of Fall Semester/Quarter), it is recommended that all chapter programming that creates liability be suspended until such educational programs have been completed and reported to the National Executive Board.",
    'paragraphs': [
      'Whenever possible, educational seminars held for your chapter should be open to all Greek organizations - or even the entire student body. Promotional and publicity assistance should be solicited from the office of the Greek Advisor. Also, university personnel should be invited to attend these programs - and should be used as educational program speakers and panelists.',
      'Program Topics',
      "The following topics are recommended as part of your educational programming, although the list certainly is not all-inclusive. Most colleges and universities have programs and presenters on these topics. These programs should be conducted annually for the chapter's entire membership of the chapter. They should be presented as early in the school year as possible.",
      'Explanation of Insurance Coverage and Risk Management Policy',
      "The fraternity's general risk management policy should be read to the chapter and each section discussed. The risk management committee should evaluate the chapter's overall programming in all areas and discuss how it relates to the risk management policy. The required educational programs should be discussed as well as each member's participation in these programs. The fraternity's general insurance policy should be discussed including coverage, limitations, exclusions, cost and named insured.",
      'Criminal Liability Education/Basic Legal Concepts Program',
      'Topics to address:',
      'Criminal liability associated with a fraternity',
      'Alcohol misuse',
      'Hazing',
      'Sexual abuse and harassment',
      'Date rape',
      'Drunk driving',
      'Illegal drug use',
      'Serving/buying for minors',
      'Party accidents/deaths',
      'Explanation of how an officer would be criminally liable for the actions of the chapter',
      'Alcohol and Drug Abuse Prevention Program',
      'Topics to Address:',
      'Drug addiction',
      'Alcoholism',
      'Substance Abuse',
      'How to identify a member who has a substance abuse problem',
      'How to deal with a member who has a substance abuse problem',
      'Effects of drugs and alcohol on the body',
      'Myths of alcohol',
      'Sexual Misconduct Prevention Program',
      'Campus resources, such as the Title IX office should be able to assist with this program. Many campuses provide students organizations with webinars for addressing various topics in this realm.',
      'Topics to Address:',
      'Understanding Campus Title IX Office and Resources',
      'Consent Education',
      'Understanding Domestic Violence and Sexual Assault',
      'Misogamy and Sexual Harassment',
      'Bystander Intervention',
      'Prevention of Sexually Transmitted Diseases and Infections',
      'Relationship Advice and Learning to be a better partner',
      'Avoiding Sexist Attitudes and Conflicts',
    ],
  },
  {
    'title': 'Sexual Misconduct Policy',
    'overview': 'Overview',
    'header': 'Nu Alpha Kappa Fraternity, Inc. will not tolerate or condone any form of sexually abusive behavior on the part of its members, whether physical, mental or emotional.',
    'summary': 'Nu Alpha Kappa Fraternity recognizes and accepts the important role we must play regarding prevention and education against sexual misconduct. As a fraternity, we value human rights and the dignity and worth of every human being, we are committed to developing and reinforcing moral character. Every member and collective chapter is expected to adhere to the highest standards of professionalism and personal conduct, to act with integrity and virtue and to respect and honor the rights of others.',
    'paragraphs': [
      'Nu Alpha Kappa Fraternity, members, alumni and affiliated organizations must comply with all federal, state, local and campus laws related to sexual misconduct. This is including, but not limited to: definitions around consent, sexual violence, sexual harassment, domestic violence, dating violence, stalking, cyberbullying and sexual exploitation.',
      'Nu Alpha Kappa Fraternity will not sponsor or participate in any activity, including competitive games and philanthropic endeavors that are abusive or demeaning to human beings. The employment or use of strippers, exotic dancers or similar, whether professional or amateur, at any fraternity activity or event as defined in the National Risk Management Policy is prohibited.',
      'As part of the annual chapter charter renewal process, all active members and chapters must attend campus or organizational sponsored awareness programs identified to help prevent sexual misconduct and harassment, better understanding of campus Title IX resources, along with educational and training resources outlined within the National Training Program and National Risk Management Education Program.',
      'Nu Alpha Kappa Fraternity applaud the efforts and empower survivors of sexual misconduct to come forward, while we support the reporting of their experiences to the appropriate authorities and believe individuals should be held accountable for wrong-doing.',
      'We have added a new avenue for reporting incidents of this nature on our NAK National Website - Incident Report.',
      'There is no place in Nu Alpha Kappa Fraternity for this type of behavior and any individuals referenced in reports shall be immediately suspended as further conduct investigations by the proper authorities are concluded. We will continue to stand by our Mission Statement and National Pillars in being Men of Mind, Men of Culture and Men of Pride and treat all members of our campus community with dignity and respect.',
      'Additional information and options can be found on the NAK National Website – Campus Title IX Resources.',
      'POLICY',
      'We, Nu Alpha Kappa Fraternity, Inc., condemn acts of sexual violence. We stand with those that are courageous enough to come forward and are committed to raise awareness and to lead in the movement to eliminate sexual violence. That is why, as a fraternal community, we commit to the following:',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
  },
  {
    'title': 'Mental Health Resources',
    'overview': 'Overview',
    'header': '',
    'summary': '',
    'paragraphs': [
      '',
      '',
      '',
    ],
  },
  {
    'title': 'Sexual Assault Prevention Resources',
    'overview': 'Overview',
    'header': '',
    'summary': '',
    'paragraphs': [
      '',
      '',
      '',
    ],
  },
  {
    'title': 'Campus Title IX Resources',
    'overview': 'Overview',
    'header': '',
    'summary': '',
    'paragraphs': [
      '',
      '',
      '',
    ],
  },
];